internal/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('<str:project>', views.index, name='index'),
    path('data/', views.data, name='data'),
    path('process/<int:id>', views.process, name='process'),
    path('login/', views.login_view, name='login'),
    path('login/submit/', views.login_submit_view, name='login_submit'),
    path('logout/', views.logout_view, name='logout'),
]

plot_service/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('', include('internal.urls')),
    path('admin/', admin.site.urls),
]

internal/models.py
from django.db import models

class Project(models.Model):
    name = models.CharField(max_length=20)
    fa_icon = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class PlotMetadata(models.Model):
    TYPES = (
        ("DP", "Demography Pie"),
        ("DB", "Demography Bar"),
        ("DS", "Demography Stacked"),
    )

    name = models.CharField(max_length=256)
    raw_data = models.FileField(upload_to='uploads/')
    orig_raw_data_filename = models.CharField(max_length=128)
    processed_data = models.FileField(upload_to='processed/')
    staff_only = models.BooleanField()
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    data_type = models.CharField(
        max_length=2,
        choices=TYPES,
        default="DP",
    )

    def __str__(self):
        return self.name

class ContentBlock(models.Model):
    TYPES = (
        ("H", "Title"),
        ("P", "Paragraph"),
        ("C", "Chart")
    )

    order = models.IntegerField()
    content_type = models.CharField(
        max_length=2,
        choices=TYPES,
        default="H",
    )
    text_content = models.TextField(blank=True)
    chart = models.ForeignKey(PlotMetadata, blank=True, null=True, default=None, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return '%s (order: %s) (text: %s) (chart: %s)' % (self.get_content_type_display(), self.order, self.text_content, self.chart)

internal/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from internal.models import *
import internal.validation as validation
from django.core.files.base import ContentFile
from django.utils.crypto import get_random_string
from internal.charts import PieChart, BarChart, StackChart
from internal.process import *
import pdb

# Create your views here.
def index(request, project):
    try:
        all_content = ContentBlock.objects.filter(project=Project.objects.get(name=project.title())).order_by('order')
    except:
        all_content = []
    processed_content = []
    for content in all_content:
        # processed data must exist and user must be staff OR user is not staff and plot is not staff only
        if content.chart:
            plt_md = content.chart
            if plt_md.processed_data and (request.user.is_staff or (not request.user.is_staff and not plt_md.staff_only)):
                if plt_md.data_type == 'DP':
                    new_chart = PieChart(
                        name=plt_md.name
                    )
                elif plt_md.data_type == 'DB':
                    new_chart = BarChart(
                        name=plt_md.name
                    )
                else:
                    new_chart = StackChart(
                        name=plt_md.name
                    )
                chart_data = processed_data_to_chart(plt_md)
                content.svg_chart = new_chart.generate(chart_data)
                processed_content.append(content)
        else:
            processed_content.append(content)
    return render(request, 'home.html', {"processed_content": processed_content, "projects": Project.objects.all()})

def data(request):
    types = PlotMetadata.TYPES
    if request.method == 'POST':
        val_obj = validation.validate_new_plot_metadata(request)
        if not val_obj[0]:
            modal_code = ['UIkit.modal("#new-data-modal").show();']
            return render(
                request, 'data.html', {
                    "types": types, 
                    "error_message": val_obj[1], 
                    "modal": modal_code,
                    "prev_req": request.POST})
        else:
            name, data_type = request.POST['name'], request.POST['data_type']
            new_metadata = PlotMetadata(name=name,
                                        data_type=data_type,
                                        raw_data=request.FILES['raw_data'],
                                        orig_raw_data_filename=request.FILES['raw_data'].name,
                                        staff_only=(request.POST['staff_only'] == 'on'))
            new_metadata.save()
            return redirect('/data')
    else:
        plt_mds = PlotMetadata.objects.all()
        for plt_md in plt_mds:
            plt_md.added = plt_md.added.strftime("%Y-%m-%d %H:%M")
        return render(request, 'data.html', {
            "types": types,
            "plt_mds": plt_mds
        })

def process(request, id):
    plt_md = PlotMetadata.objects.get(pk=id)
    processed_data = process_raw_data(plt_md)
    plt_md.processed_data.save('processed_' + get_random_string(length=6) + '_' + plt_md.orig_raw_data_filename, ContentFile(processed_data.to_csv()))
    plt_md.save()
    return redirect('/data')

def login_view(request):
    if request.user.is_authenticated:
        return redirect('/')
    return render(request, 'login.html')

def login_submit_view(request):
    user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        return redirect('/')
    return render(request, 'login.html', {
        'error_message': "Failed to authenticate.",
    })

def logout_view(request):
    logout(request)
    return redirect('/login/')

internal/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <title>Abbot Dashboard</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8">
        <!-- UIkit CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.8/css/uikit.min.css" />

        <!-- UIkit JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.8/js/uikit.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.8/js/uikit-icons.min.js"></script>

        <!-- Pygal js -->
        <script type="text/javascript" src="http://kozea.github.com/pygal.js/latest/pygal-tooltips.min.js"></script>

        <!-- Custom Stylesheet -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    </head>
    <body>
        <nav class="uk-navbar-container" uk-navbar>
            <div class="uk-navbar-left uk-margin-left">
                <a class="uk-navbar-item uk-logo" href="#">Abbot Dashboard</a>
            </div>
            <div class="uk-navbar-right uk-margin-right">
                <ul class="uk-navbar-nav">
                    <li class="nav-item">
                        <a href="/">
                            <div>
                                <span uk-icon="social"></span>
                                <div class="uk-navbar-subtitle">Plots</div>
                            </div>
                        </a>
                    </li>
                    {% if user.is_authenticated == False %}
                        <li class="nav-item">
                            <a href="{% url 'login' %}">
                                <div>
                                    <span uk-icon="sign-in"></span>
                                    <div class="uk-navbar-subtitle">login</div>
                                </div>
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'data' %}">
                                <div>
                                    <span uk-icon="folder"></span>
                                    <div class="uk-navbar-subtitle">Data</div>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item">
                                <a href="/admin">
                                    <div>
                                        <span uk-icon="settings"></span>
                                        <div class="uk-navbar-subtitle">Admin</div>
                                    </div>
                                </a>
                            </li>
                        <li class="nav-item">
                            <a href="{% url 'logout' %}">
                                <div>
                                    <span uk-icon="sign-out"></span>
                                    <div class="uk-navbar-subtitle">Logout</div>
                                </div>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="uk-container uk-container-expand uk-margin-medium-top uk-margin-medium-bottom">
            {% block content %}{% endblock %}
        </div>
        <script>
            {% for line in modal %}
                {{ line | safe }}
            {% endfor %}
        </script>
    </body>
</html>

internal/templates/data.html
{% extends "base.html" %}

{% block content %}

<!-- Form Modal, which is shown if new is pressed -->
<div id="new-data-modal" class="uk-flex-top" uk-modal>
    <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">
        <button class="uk-modal-close-default" type="button" uk-close></button>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="uk-fieldset">
                <legend class="uk-legend">Upload Plot Metadata</legend>

                {% if error_message %}
                    <div class="uk-alert-danger" uk-alert>
                            <a class="uk-alert-close" uk-close></a>
                            <p class="">{{ error_message }}</p>
                    </div>
                {% endif %}
            
                <div class="uk-margin">
                    <input class="uk-input" type="text" name="name" placeholder="Plot Name" value="{{ prev_req.name}}">
                </div>
                <div class="uk-margin" uk-margin>
                    <div uk-form-custom="target: true">
                        <input name="raw_data" type="file">
                        <input class="uk-input uk-form-width-medium" type="text" placeholder="Select Raw Data" disabled>
                    </div>
                    <div uk-form-custom="target: > * > span:first-child">
                        <select name="data_type">
                            <option value="">Plot & Data Type</option>
                            {% for type in types %}
                                <option value="{{type.0}}">Type: {{type.1}}</option>
                            {% endfor %}
                        </select>
                        <button class="uk-button uk-button-default" type="button" tabindex="-1">
                            <span></span>
                            <span uk-icon="icon: chevron-down"></span>
                        </button>
                    </div>
                </div>
                <div>
                    <label><input class="uk-checkbox" name="staff_only" type="checkbox" checked> Visible By Staff Only</label>
                </div>
                <button class="uk-button uk-button-default uk-margin-top">Submit</button>
            </fieldset>
        </form>
    </div>
</div>

<!-- Page Content -->
<div class="uk-card">
    <div class="uk-card-header">
        <div uk-grid>
            <div class="uk-width-5-6@s">
                <h3 class="uk-card-title">Upload, Process, and Plot Data</h3>
            </div>
            <div class="uk-width-1-6@s">
                <a class="uk-button uk-button-primary" href="#new-data-modal" uk-toggle>New <span class="uk-margin-left" uk-icon="plus-circle"></span></a>
            </div>
        </div>
    </div>
    <div class="uk-card-body">
        <table class="uk-table uk-table-divider">
            <caption></caption>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Staff Only</th>
                    <th>Raw Data</th>
                    <th>Plot & Data Type</th>
                    <th>Added</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for plt_md in plt_mds %}
                    <tr>
                        <td>{{ plt_md.name }}</td>
                        <td>{{ plt_md.staff_only }}</td>
                        <td>{{ plt_md.orig_raw_data_filename }}</td>
                        <td>{{ plt_md.get_data_type_display }}</td>
                        <td>{{ plt_md.added }}</td>
                        <td>
                            {% if plt_md.processed_data %}
                                <p class="uk-text-success"> Processed <span uk-icon="check"></span></p>
                            {% else %}
                                <p class="uk-text-success"> Unprocessed <span uk-icon="close"></span></p>
                            {% endif %}
                        </td>
                        <td>
                            <a class="uk-button uk-button-primary" href="/process/{{plt_md.id}}" uk-toggle>Process</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="uk-card-footer"></div>
</div>
{% endblock %}

internal/templates/home.html
{% extends "base.html" %}

{% block content %}

<div uk-grid>
    <!-- begin sidebar -->
    <div class="uk-width-1-6@s">
        <ul class="uk-nav-default uk-nav-parent-icon text-sidebar" uk-nav>
            <li class="uk-nav-header text-sidebar">Projects</li>
            {% for project in projects %}
                <li><a href="/{{project.name.lower}}"><span class="uk-margin-small-right"><i class="fas fa-{{project.fa_icon}}"></i></span> {{project.name}}</a></li>
            {% endfor %}
        </ul>
    </div>

    <!-- begin content -->
    <div class="uk-width-expand@m">
        <div uk-grid>
            {% for content_block in processed_content %}
                {% if content_block.content_type == 'H' %}
                <div class="uk-width-1-1">
                    <h1 class="uk-text-lead">{{content_block.text_content}}</h1>
                <div class="uk-width-1-1">
                {% elif content_block.content_type == 'P' %}
                <div class="uk-width-1-1">
                    <p>{{content_block.text_content}}</p>
                <div class="uk-width-1-1">
                {% else %}
                    <div class="uk-width-1-2">
                        {{ content_block.svg_chart|safe }}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

internal/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="uk-container uk-container-small">

    <div class="uk-child-width-1-2@m uk-grid-medium uk-grid-match uk-flex-center" uk-grid>
        <div>
            <div class="uk-card uk-card-default uk-card-body uk-margin-top">
                <form action="{% url 'login_submit' %}" method="post">
                    {% csrf_token %}
                    <fieldset class="uk-fieldset">
                    <legend class="uk-legend">Please Log In</legend>
                    {% if error_message %}
                    <div class="uk-alert-danger" uk-alert>
                            <a class="uk-alert-close" uk-close></a>
                            <p class="">{{ error_message }}</p>
                    </div>
                    {% endif %}
                    <div class="uk-margin"><input class="uk-input" type="text" placeholder="username" name="username"></div>
                    <div class="uk-margin"><input class="uk-input" type="password" placeholder="password" name="password"></div>
                    </fieldset>
                    <input type="submit" class="uk-button uk-button-default" value="Login &rarrb;">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}